//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackBaron.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InvertedEffect {
            get {
                return ((bool)(this["InvertedEffect"]));
            }
            set {
                this["InvertedEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimedColorsEffect {
            get {
                return ((bool)(this["TimedColorsEffect"]));
            }
            set {
                this["TimedColorsEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GlowEffect {
            get {
                return ((bool)(this["GlowEffect"]));
            }
            set {
                this["GlowEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DistortionEffect {
            get {
                return ((bool)(this["DistortionEffect"]));
            }
            set {
                this["DistortionEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BumpEffect {
            get {
                return ((bool)(this["BumpEffect"]));
            }
            set {
                this["BumpEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GreenShiftEffect {
            get {
                return ((bool)(this["GreenShiftEffect"]));
            }
            set {
                this["GreenShiftEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ColorWringEffect {
            get {
                return ((bool)(this["ColorWringEffect"]));
            }
            set {
                this["ColorWringEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FullScreen {
            get {
                return ((bool)(this["FullScreen"]));
            }
            set {
                this["FullScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SoundOn {
            get {
                return ((bool)(this["SoundOn"]));
            }
            set {
                this["SoundOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BloomEffect {
            get {
                return ((bool)(this["BloomEffect"]));
            }
            set {
                this["BloomEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BloomIndex {
            get {
                return ((int)(this["BloomIndex"]));
            }
            set {
                this["BloomIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public global::Microsoft.Xna.Framework.Input.Keys Key0 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Key0"]));
            }
            set {
                this["Key0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public global::Microsoft.Xna.Framework.Input.Keys Key1 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Key1"]));
            }
            set {
                this["Key1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::Microsoft.Xna.Framework.Input.Keys Key2 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Key2"]));
            }
            set {
                this["Key2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::Microsoft.Xna.Framework.Input.Keys Key3 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Key3"]));
            }
            set {
                this["Key3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter")]
        public global::Microsoft.Xna.Framework.Input.Keys Key4 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Key4"]));
            }
            set {
                this["Key4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public global::Microsoft.Xna.Framework.Input.Keys Key5 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Key5"]));
            }
            set {
                this["Key5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q")]
        public global::Microsoft.Xna.Framework.Input.Keys Key6 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Key6"]));
            }
            set {
                this["Key6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::Microsoft.Xna.Framework.Input.Keys Key7 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Key7"]));
            }
            set {
                this["Key7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Button0 {
            get {
                return ((int)(this["Button0"]));
            }
            set {
                this["Button0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Button1 {
            get {
                return ((int)(this["Button1"]));
            }
            set {
                this["Button1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Button2 {
            get {
                return ((int)(this["Button2"]));
            }
            set {
                this["Button2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Button3 {
            get {
                return ((int)(this["Button3"]));
            }
            set {
                this["Button3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Button4 {
            get {
                return ((int)(this["Button4"]));
            }
            set {
                this["Button4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Button5 {
            get {
                return ((int)(this["Button5"]));
            }
            set {
                this["Button5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int Button6 {
            get {
                return ((int)(this["Button6"]));
            }
            set {
                this["Button6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Button7 {
            get {
                return ((int)(this["Button7"]));
            }
            set {
                this["Button7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int Button8 {
            get {
                return ((int)(this["Button8"]));
            }
            set {
                this["Button8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int Button9 {
            get {
                return ((int)(this["Button9"]));
            }
            set {
                this["Button9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U")]
        public global::Microsoft.Xna.Framework.Input.Keys Key8 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Key8"]));
            }
            set {
                this["Key8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U")]
        public global::Microsoft.Xna.Framework.Input.Keys Key9 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Key9"]));
            }
            set {
                this["Key9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::Microsoft.Xna.Framework.Input.Keys Key10 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Key10"]));
            }
            set {
                this["Key10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::Microsoft.Xna.Framework.Input.Keys Key11 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Key11"]));
            }
            set {
                this["Key11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::Microsoft.Xna.Framework.Input.Keys Key12 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Key12"]));
            }
            set {
                this["Key12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::Microsoft.Xna.Framework.Input.Keys Key13 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Key13"]));
            }
            set {
                this["Key13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public global::Microsoft.Xna.Framework.Input.Keys PKey0 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["PKey0"]));
            }
            set {
                this["PKey0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public global::Microsoft.Xna.Framework.Input.Keys PKey1 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["PKey1"]));
            }
            set {
                this["PKey1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::Microsoft.Xna.Framework.Input.Keys PKey2 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["PKey2"]));
            }
            set {
                this["PKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::Microsoft.Xna.Framework.Input.Keys PKey3 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["PKey3"]));
            }
            set {
                this["PKey3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter")]
        public global::Microsoft.Xna.Framework.Input.Keys PKey4 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["PKey4"]));
            }
            set {
                this["PKey4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public global::Microsoft.Xna.Framework.Input.Keys PKey5 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["PKey5"]));
            }
            set {
                this["PKey5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q")]
        public global::Microsoft.Xna.Framework.Input.Keys PKey6 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["PKey6"]));
            }
            set {
                this["PKey6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::Microsoft.Xna.Framework.Input.Keys PKey7 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["PKey7"]));
            }
            set {
                this["PKey7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U")]
        public global::Microsoft.Xna.Framework.Input.Keys PKey8 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["PKey8"]));
            }
            set {
                this["PKey8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U")]
        public global::Microsoft.Xna.Framework.Input.Keys PKey9 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["PKey9"]));
            }
            set {
                this["PKey9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::Microsoft.Xna.Framework.Input.Keys PKey10 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["PKey10"]));
            }
            set {
                this["PKey10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::Microsoft.Xna.Framework.Input.Keys PKey11 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["PKey11"]));
            }
            set {
                this["PKey11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::Microsoft.Xna.Framework.Input.Keys PKey12 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["PKey12"]));
            }
            set {
                this["PKey12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::Microsoft.Xna.Framework.Input.Keys PKey13 {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["PKey13"]));
            }
            set {
                this["PKey13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96")]
        public int Button10 {
            get {
                return ((int)(this["Button10"]));
            }
            set {
                this["Button10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("97")]
        public int Button11 {
            get {
                return ((int)(this["Button11"]));
            }
            set {
                this["Button11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("98")]
        public int Button12 {
            get {
                return ((int)(this["Button12"]));
            }
            set {
                this["Button12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public int Button13 {
            get {
                return ((int)(this["Button13"]));
            }
            set {
                this["Button13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PButton0 {
            get {
                return ((int)(this["PButton0"]));
            }
            set {
                this["PButton0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PButton1 {
            get {
                return ((int)(this["PButton1"]));
            }
            set {
                this["PButton1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PButton2 {
            get {
                return ((int)(this["PButton2"]));
            }
            set {
                this["PButton2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int PButton3 {
            get {
                return ((int)(this["PButton3"]));
            }
            set {
                this["PButton3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int PButton4 {
            get {
                return ((int)(this["PButton4"]));
            }
            set {
                this["PButton4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int PButton5 {
            get {
                return ((int)(this["PButton5"]));
            }
            set {
                this["PButton5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int PButton6 {
            get {
                return ((int)(this["PButton6"]));
            }
            set {
                this["PButton6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int PButton7 {
            get {
                return ((int)(this["PButton7"]));
            }
            set {
                this["PButton7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int PButton8 {
            get {
                return ((int)(this["PButton8"]));
            }
            set {
                this["PButton8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int PButton9 {
            get {
                return ((int)(this["PButton9"]));
            }
            set {
                this["PButton9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96")]
        public int PButton10 {
            get {
                return ((int)(this["PButton10"]));
            }
            set {
                this["PButton10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("97")]
        public int PButton11 {
            get {
                return ((int)(this["PButton11"]));
            }
            set {
                this["PButton11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("98")]
        public int PButton12 {
            get {
                return ((int)(this["PButton12"]));
            }
            set {
                this["PButton12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public int PButton13 {
            get {
                return ((int)(this["PButton13"]));
            }
            set {
                this["PButton13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFlag0 {
            get {
                return ((bool)(this["PFlag0"]));
            }
            set {
                this["PFlag0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFlag1 {
            get {
                return ((bool)(this["PFlag1"]));
            }
            set {
                this["PFlag1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFlag2 {
            get {
                return ((bool)(this["PFlag2"]));
            }
            set {
                this["PFlag2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFlag3 {
            get {
                return ((bool)(this["PFlag3"]));
            }
            set {
                this["PFlag3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFlag4 {
            get {
                return ((bool)(this["PFlag4"]));
            }
            set {
                this["PFlag4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFlag5 {
            get {
                return ((bool)(this["PFlag5"]));
            }
            set {
                this["PFlag5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFlag6 {
            get {
                return ((bool)(this["PFlag6"]));
            }
            set {
                this["PFlag6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFlag7 {
            get {
                return ((bool)(this["PFlag7"]));
            }
            set {
                this["PFlag7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFlag8 {
            get {
                return ((bool)(this["PFlag8"]));
            }
            set {
                this["PFlag8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFlag9 {
            get {
                return ((bool)(this["PFlag9"]));
            }
            set {
                this["PFlag9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFlag10 {
            get {
                return ((bool)(this["PFlag10"]));
            }
            set {
                this["PFlag10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFlag11 {
            get {
                return ((bool)(this["PFlag11"]));
            }
            set {
                this["PFlag11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFlag12 {
            get {
                return ((bool)(this["PFlag12"]));
            }
            set {
                this["PFlag12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFlag13 {
            get {
                return ((bool)(this["PFlag13"]));
            }
            set {
                this["PFlag13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool P2Flag0 {
            get {
                return ((bool)(this["P2Flag0"]));
            }
            set {
                this["P2Flag0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool P2Flag1 {
            get {
                return ((bool)(this["P2Flag1"]));
            }
            set {
                this["P2Flag1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool P2Flag2 {
            get {
                return ((bool)(this["P2Flag2"]));
            }
            set {
                this["P2Flag2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool P2Flag3 {
            get {
                return ((bool)(this["P2Flag3"]));
            }
            set {
                this["P2Flag3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool P2Flag4 {
            get {
                return ((bool)(this["P2Flag4"]));
            }
            set {
                this["P2Flag4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool P2Flag5 {
            get {
                return ((bool)(this["P2Flag5"]));
            }
            set {
                this["P2Flag5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool P2Flag6 {
            get {
                return ((bool)(this["P2Flag6"]));
            }
            set {
                this["P2Flag6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool P2Flag7 {
            get {
                return ((bool)(this["P2Flag7"]));
            }
            set {
                this["P2Flag7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool P2Flag8 {
            get {
                return ((bool)(this["P2Flag8"]));
            }
            set {
                this["P2Flag8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool P2Flag9 {
            get {
                return ((bool)(this["P2Flag9"]));
            }
            set {
                this["P2Flag9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool P2Flag10 {
            get {
                return ((bool)(this["P2Flag10"]));
            }
            set {
                this["P2Flag10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool P2Flag11 {
            get {
                return ((bool)(this["P2Flag11"]));
            }
            set {
                this["P2Flag11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool P2Flag12 {
            get {
                return ((bool)(this["P2Flag12"]));
            }
            set {
                this["P2Flag12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool P2Flag13 {
            get {
                return ((bool)(this["P2Flag13"]));
            }
            set {
                this["P2Flag13"] = value;
            }
        }
    }
}
